loading app /mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py
loading app ryu.controller.ofp_handler
instantiating app /mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py of LeftSlice
instantiating app ryu.controller.ofp_handler of OFPHandler
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 55184)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s5 (in_port=4)
INFO packet arrived in s5 (in_port=4)
INFO sending packet from s5 (out_port=5)
INFO packet arrived in s4 (in_port=5)
INFO packet arrived in s4 (in_port=5)
INFO sending packet from s4 (out_port=4)
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=4)
INFO packet arrived in s4 (in_port=4)
INFO sending packet from s4 (out_port=5)
INFO packet arrived in s5 (in_port=5)
INFO packet arrived in s5 (in_port=5)
INFO sending packet from s5 (out_port=4)
INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50278)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
Error in the datapath 0000000000000001 from ('10.244.1.26', 50284)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50288)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50294)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50298)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50300)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50316)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 50324)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 43626)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 43638)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 43652)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 42840)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 42856)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 42868)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s5 (in_port=4)
INFO packet arrived in s5 (in_port=4)
INFO sending packet from s5 (out_port=5)
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 42884)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s1 (in_port=1)
INFO packet arrived in s1 (in_port=1)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 47870)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=3)
INFO packet arrived in s4 (in_port=3)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 3
INFO packet arrived in s4 (in_port=2)
INFO packet arrived in s4 (in_port=2)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 2
INFO packet arrived in s5 (in_port=1)
INFO packet arrived in s5 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s4 (in_port=1)
INFO packet arrived in s4 (in_port=1)
LeftSlice: Exception occurred during handler processing. Backtrace from offending handler [_packet_in_handler] servicing event [EventOFPPacketIn] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/mnt/mounting/cloud-sdn/slicing-script/fat-tree/left-slice.py", line 126, in _packet_in_handler
    out_port = self.non_edge_sw_port[dpid][in_port]
KeyError: 1
INFO packet arrived in s1 (in_port=2)
INFO packet arrived in s1 (in_port=2)
INFO sending packet from s1 (out_port=0)
Error in the datapath 0000000000000001 from ('10.244.1.26', 47880)
hub: uncaught exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 551, in datapath_connection_factory
    datapath.serve()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 469, in serve
    self._recv_loop()
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 211, in deactivate
    method(self)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/controller.py", line 370, in _recv_loop
    handler(ev)
  File "/usr/local/lib/python3.8/site-packages/ryu/controller/ofp_handler.py", line 281, in error_msg_handler
    if msg.type == ofp.OFPET_EXPERIMENTER:
AttributeError: module 'ryu.ofproto.ofproto_v1_0' has no attribute 'OFPET_EXPERIMENTER'

INFO packet arrived in s4 (in_port=4)
INFO packet arrived in s4 (in_port=4)
INFO sending packet from s4 (out_port=5)
INFO packet arrived in s4 (in_port=5)
INFO packet arrived in s4 (in_port=5)
INFO sending packet from s4 (out_port=4)
INFO packet arrived in s5 (in_port=5)
INFO packet arrived in s5 (in_port=5)
INFO sending packet from s5 (out_port=4)
^C